#!/bin/bash
set -e

case "$1" in
    configure)

        # Add permanent firewall rules (ignore errors if already exist)
        #firewall-cmd --permanent --zone=public --add-service=ns2 2>/dev/null || true
        firewall-cmd --permanent --zone=public --add-service=ssh 2>/dev/null || true
        #firewall-cmd --permanent --zone=public --add-service=http 2>/dev/null || true
        firewall-cmd --permanent --zone=public --add-service=https 2>/dev/null || true
        firewall-cmd --permanent --zone=public --add-service=snmp 2>/dev/null || true

        # Reload to apply changes
        #firewall-cmd --reload 2>/dev/null || true

        mkdir -p /etc/nginx/ssl

        if [ ! -f /etc/nginx/ssl/selfsigned.key ] || [ ! -f /etc/nginx/ssl/selfsigned.crt ]; then
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/selfsigned.key -out /etc/nginx/ssl/selfsigned.crt -subj "/C=US/ST=Missouri/L=Independence/O=ns2/CN=var"
        fi

        rm -f /etc/nginx/sites-enabled/default
        ln -sf /etc/nginx/sites-available/ns2-ui.conf /etc/nginx/sites-enabled/

        systemctl reload nginx 2>/dev/null || true

        ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
esac

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'ns2-dbus.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ns2-dbus.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ns2-dbus.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ns2-dbus.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'ns2-ui.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'ns2-ui.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'ns2-ui.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'ns2-ui.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'ns2-dbus.service' 'ns2-ui.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0